[build]
  base = "."
  publish = "dist/public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefer-offline --no-audit"

# For static site hosting (API will be separate)
[build.processing]
  skip_processing = false

# Client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set these in Netlify dashboard)
# DATABASE_URL
# SESSION_SECRET
# NODE_ENV
# STRIPE_SECRET_KEY
# VITE_STRIPE_PUBLIC_KEY
# SENDGRID_API_KEY